import json

import pytest

from subscriptions.subscription_salesforce_service import SalesforceSubscriptionService


# @pytest.fixture(autouse=True)
# @pytest.fixture
# def mocked_donor_id(mocker):
#     mocker.patch.object(SalesforceDonorService, 'exists_by_email', return_value="123456")


# @pytest.fixture(autouse=True)
@pytest.fixture
def mocked_sf_recurring_donation_id(mocker):
    mocker.patch.object(SalesforceSubscriptionService, 'exists', return_value={'id': '12345', 'sf_contact_id': '12345'})

@pytest.fixture
def mocked_subscription_schedule():
    return {
  "application": None,
  "canceled_at": None,
  "completed_at": None,
  "created": 1735245775,
  "current_phase": {
    "end_date": 1740114000,
    "start_date": 1737435600
  },
  "customer": "cus_RTKTPO89z5Ge53",
  "default_settings": {
    "application_fee_percent": None,
    "automatic_tax": {
      "disabled_reason": None,
      "enabled": False,
      "liability": None
    },
    "billing_cycle_anchor": "automatic",
    "billing_thresholds": None,
    "collection_method": "charge_automatically",
    "default_payment_method": None,
    "default_source": None,
    "description": None,
    "invoice_settings": {
      "account_tax_ids": None,
      "days_until_due": None,
      "issuer": {
        "type": "self"
      }
    },
    "on_behalf_of": None,
    "transfer_data": None
  },
  "end_behavior": "release",
  "id": "sub_sched_1QaNtTL1MLd6bigC9AQHNWKK",
  "livemode": False,
  "metadata": {
    "anetSubscriptionId": "65804855"
  },
  "object": "subscription_schedule",
  "phases": [
    {
      "add_invoice_items": [],
      "application_fee_percent": None,
      "billing_cycle_anchor": None,
      "billing_thresholds": None,
      "collection_method": None,
      "coupon": None,
      "currency": "usd",
      "default_payment_method": None,
      "default_tax_rates": [],
      "description": None,
      "discounts": [],
      "end_date": 1740114000,
      "invoice_settings": None,
      "items": [
        {
          "billing_thresholds": None,
          "discounts": [],
          "metadata": {},
          "plan": "price_1QPdeSL1MLd6bigC8hHq4zFm",
          "price": "price_1QPdeSL1MLd6bigC8hHq4zFm",
          "quantity": 1,
          "tax_rates": []
        }
      ],
      "metadata": {},
      "on_behalf_of": None,
      "proration_behavior": "create_prorations",
      "start_date": 1737435600,
      "transfer_data": None,
      "trial_end": None
    }
  ],
  "released_at": None,
  "released_subscription": None,
  "renewal_interval": None,
  "status": "active",
  "subscription": "sub_1QjZZiL1MLd6bigC1zMiPpEz",
  "test_clock": None
}

@pytest.fixture
def active_subscription_create_event_no_anet_import():
    return {
    "id": "evt_1QoboAL1MLd6bigCMJJX4qVr",
    "object": "event",
    "api_version": "2022-11-15",
    "created": 1738635854,
    "data": {
        "object": {
            "id": "sub_1Qobo8L1MLd6bigCdCPbW1yJ",
            "object": "subscription",
            "application": "ca_EEtbhRJHFK2etIhjyxcqXqBw3Ck05bKK",
            "application_fee_percent": None,
            "automatic_tax": {
                "disabled_reason": None,
                "enabled": False,
                "liability": None
            },
            "billing_cycle_anchor": 1738635852,
            "billing_cycle_anchor_config": None,
            "billing_thresholds": None,
            "cancel_at": None,
            "cancel_at_period_end": False,
            "canceled_at": None,
            "cancellation_details": {
                "comment": None,
                "feedback": None,
                "reason": None
            },
            "collection_method": "charge_automatically",
            "created": 1738635852,
            "currency": "usd",
            "current_period_end": 1741055052,
            "current_period_start": 1738635852,
            "customer": "cus_Ri1rdtAt1mwmBK",
            "days_until_due": None,
            "default_payment_method": "pm_1Qobo7L1MLd6bigCreMS3M9o",
            "default_source": None,
            "default_tax_rates": [],
            "description": None,
            "discount": None,
            "discounts": [],
            "ended_at": None,
            "invoice_settings": {
                "account_tax_ids": None,
                "issuer": {
                    "type": "self"
                }
            },
            "items": {
                "object": "list",
                "data": [
                    {
                        "id": "si_Ri1rozq1wO67dX",
                        "object": "subscription_item",
                        "billing_thresholds": None,
                        "created": 1738635853,
                        "discounts": [],
                        "metadata": {},
                        "plan": {
                            "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                            "object": "plan",
                            "active": True,
                            "aggregate_usage": None,
                            "amount": 100,
                            "amount_decimal": "100",
                            "billing_scheme": "per_unit",
                            "created": 1711218898,
                            "currency": "usd",
                            "interval": "month",
                            "interval_count": 1,
                            "livemode": False,
                            "metadata": {},
                            "meter": None,
                            "nickname": None,
                            "product": "prod_Pn9imCT8L9sSWq",
                            "tiers_mode": None,
                            "transform_usage": None,
                            "trial_period_days": None,
                            "usage_type": "licensed"
                        },
                        "price": {
                            "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                            "object": "price",
                            "active": True,
                            "billing_scheme": "per_unit",
                            "created": 1711218898,
                            "currency": "usd",
                            "custom_unit_amount": None,
                            "livemode": False,
                            "lookup_key": None,
                            "metadata": {},
                            "nickname": None,
                            "product": "prod_Pn9imCT8L9sSWq",
                            "recurring": {
                                "aggregate_usage": None,
                                "interval": "month",
                                "interval_count": 1,
                                "meter": None,
                                "trial_period_days": None,
                                "usage_type": "licensed"
                            },
                            "tax_behavior": "exclusive",
                            "tiers_mode": None,
                            "transform_quantity": None,
                            "type": "recurring",
                            "unit_amount": 100,
                            "unit_amount_decimal": "100"
                        },
                        "quantity": 51,
                        "subscription": "sub_1Qobo8L1MLd6bigCdCPbW1yJ",
                        "tax_rates": []
                    }
                ],
                "has_more": False,
                "total_count": 1,
                "url": "/v1/subscription_items?subscription=sub_1Qobo8L1MLd6bigCdCPbW1yJ"
            },
            "latest_invoice": "in_1Qobo9L1MLd6bigC6N5HMhwV",
            "livemode": False,
            "metadata": {
                "campaign_code": "F000",
                "created_by": "FormAssembly - Stripe Test Connector - Reference: Form 5156970 / Conn. 808220 / Resp. 369533944"
            },
            "next_pending_invoice_item_invoice": None,
            "on_behalf_of": None,
            "pause_collection": None,
            "payment_settings": {
                "payment_method_options": None,
                "payment_method_types": None,
                "save_default_payment_method": "off"
            },
            "pending_invoice_item_interval": None,
            "pending_setup_intent": None,
            "pending_update": None,
            "plan": {
                "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                "object": "plan",
                "active": True,
                "aggregate_usage": None,
                "amount": 100,
                "amount_decimal": "100",
                "billing_scheme": "per_unit",
                "created": 1711218898,
                "currency": "usd",
                "interval": "month",
                "interval_count": 1,
                "livemode": False,
                "metadata": {},
                "meter": None,
                "nickname": None,
                "product": "prod_Pn9imCT8L9sSWq",
                "tiers_mode": None,
                "transform_usage": None,
                "trial_period_days": None,
                "usage_type": "licensed"
            },
            "quantity": 51,
            "schedule": None,
            "start_date": 1738635852,
            "status": "incomplete",
            "test_clock": None,
            "transfer_data": None,
            "trial_end": None,
            "trial_settings": {
                "end_behavior": {
                    "missing_payment_method": "create_invoice"
                }
            },
            "trial_start": None
        }
    },
    "livemode": False,
    "pending_webhooks": 0,
    "request": {
        "id": "req_7BdPAeznvEboW0",
        "idempotency_key": "155d9ddf-1e27-4ed1-9046-bc32d45ff66c"
    },
    "type": "customer.subscription.created"
}

@pytest.fixture
def subscription_create_event_with_anet_import():
    return {
  "object": {
    "id": "sub_1QjZZiL1MLd6bigC1zMiPpEz",
    "object": "subscription",
    "application": None,
    "application_fee_percent": None,
    "automatic_tax": {
      "disabled_reason": None,
      "enabled": False,
      "liability": None
    },
    "billing_cycle_anchor": 1737435600,
    "billing_cycle_anchor_config": None,
    "billing_thresholds": None,
    "cancel_at": None,
    "cancel_at_period_end": False,
    "canceled_at": None,
    "cancellation_details": {
      "comment": None,
      "feedback": None,
      "reason": None
    },
    "collection_method": "charge_automatically",
    "created": 1737435600,
    "currency": "usd",
    "current_period_end": 1740114000,
    "current_period_start": 1737435600,
    "customer": "cus_RTKTPO89z5Ge53",
    "days_until_due": None,
    "default_payment_method": None,
    "default_source": None,
    "default_tax_rates": [],
    "description": None,
    "discount": None,
    "discounts": [],
    "ended_at": None,
    "invoice_settings": {
      "account_tax_ids": None,
      "issuer": {
        "type": "self"
      }
    },
    "items": {
      "object": "list",
      "data": [
        {
          "id": "si_RcpEwuWfoPFsnS",
          "object": "subscription_item",
          "billing_thresholds": None,
          "created": 1737435631,
          "discounts": [],
          "metadata": {},
          "plan": {
            "id": "price_1QPdeSL1MLd6bigC8hHq4zFm",
            "object": "plan",
            "active": True,
            "aggregate_usage": None,
            "amount": 5000,
            "amount_decimal": "5000",
            "billing_scheme": "per_unit",
            "created": 1732684740,
            "currency": "usd",
            "interval": "month",
            "interval_count": 1,
            "livemode": False,
            "metadata": {},
            "meter": None,
            "nickname": None,
            "product": "prod_RIDuesaY2hbu6F",
            "tiers_mode": None,
            "transform_usage": None,
            "trial_period_days": None,
            "usage_type": "licensed"
          },
          "price": {
            "id": "price_1QPdeSL1MLd6bigC8hHq4zFm",
            "object": "price",
            "active": True,
            "billing_scheme": "per_unit",
            "created": 1732684740,
            "currency": "usd",
            "custom_unit_amount": None,
            "livemode": False,
            "lookup_key": "1_month_5000_recurring_donation",
            "metadata": {},
            "nickname": None,
            "product": "prod_RIDuesaY2hbu6F",
            "recurring": {
              "aggregate_usage": None,
              "interval": "month",
              "interval_count": 1,
              "meter": None,
              "trial_period_days": None,
              "usage_type": "licensed"
            },
            "tax_behavior": "unspecified",
            "tiers_mode": None,
            "transform_quantity": None,
            "type": "recurring",
            "unit_amount": 5000,
            "unit_amount_decimal": "5000"
          },
          "quantity": 1,
          "subscription": "sub_1QjZZiL1MLd6bigC1zMiPpEz",
          "tax_rates": []
        }
      ],
      "has_more": False,
      "total_count": 1,
      "url": "/v1/subscription_items?subscription=sub_1QjZZiL1MLd6bigC1zMiPpEz"
    },
    "latest_invoice": "in_1QjZZiL1MLd6bigCgdJSDASj",
    "livemode": False,
    "metadata": {},
    "next_pending_invoice_item_invoice": None,
    "on_behalf_of": None,
    "pause_collection": None,
    "payment_settings": {
      "payment_method_options": None,
      "payment_method_types": None,
      "save_default_payment_method": None
    },
    "pending_invoice_item_interval": None,
    "pending_setup_intent": None,
    "pending_update": None,
    "plan": {
      "id": "price_1QPdeSL1MLd6bigC8hHq4zFm",
      "object": "plan",
      "active": True,
      "aggregate_usage": None,
      "amount": 5000,
      "amount_decimal": "5000",
      "billing_scheme": "per_unit",
      "created": 1732684740,
      "currency": "usd",
      "interval": "month",
      "interval_count": 1,
      "livemode": False,
      "metadata": {},
      "meter": None,
      "nickname": None,
      "product": "prod_RIDuesaY2hbu6F",
      "tiers_mode": None,
      "transform_usage": None,
      "trial_period_days": None,
      "usage_type": "licensed"
    },
    "quantity": 1,
    "schedule": "sub_sched_1QaNtTL1MLd6bigC9AQHNWKK",
    "start_date": 1737435600,
    "status": "active",
    "test_clock": None,
    "transfer_data": None,
    "trial_end": None,
    "trial_settings": {
      "end_behavior": {
        "missing_payment_method": "create_invoice"
      }
    },
    "trial_start": None
  },
  "previous_attributes": None
}

@pytest.fixture
def fixed_active_subscription_dict():
    return {
    "id": "evt_1QjZZjL1MLd6bigC1mQePBRn",
    "object": "event",
    "api_version": "2022-11-15",
    "created": 1737435631,
    "data": {
        "object": {
            "id": "sub_1QjZZiL1MLd6bigC1zMiPpEz",
            "object": "subscription",
            "application": None,
            "application_fee_percent": None,
            "automatic_tax": {
                "disabled_reason": None,
                "enabled": False,
                "liability": None
            },
            "billing_cycle_anchor": 1737435600,
            "billing_cycle_anchor_config": None,
            "billing_thresholds": None,
            "cancel_at": None,
            "cancel_at_period_end": False,
            "canceled_at": None,
            "cancellation_details": {
                "comment": None,
                "feedback": None,
                "reason": None
            },
            "collection_method": "charge_automatically",
            "created": 1737435600,
            "currency": "usd",
            "current_period_end": 1740114000,
            "current_period_start": 1737435600,
            "customer": "cus_RTKTPO89z5Ge53",
            "days_until_due": None,
            "default_payment_method": None,
            "default_source": None,
            "default_tax_rates": [],
            "description": None,
            "discount": None,
            "discounts": [],
            "ended_at": None,
            "invoice_settings": {
                "account_tax_ids": None,
                "issuer": {
                    "type": "self"
                }
            },
            "items": {
                "object": "list",
                "data": [
                    {
                        "id": "si_RcpEwuWfoPFsnS",
                        "object": "subscription_item",
                        "billing_thresholds": None,
                        "created": 1737435631,
                        "discounts": [],
                        "metadata": {},
                        "plan": {
                            "id": "price_1QPdeSL1MLd6bigC8hHq4zFm",
                            "object": "plan",
                            "active": True,
                            "aggregate_usage": None,
                            "amount": 5000,
                            "amount_decimal": "5000",
                            "billing_scheme": "per_unit",
                            "created": 1732684740,
                            "currency": "usd",
                            "interval": "month",
                            "interval_count": 1,
                            "livemode": False,
                            "metadata": {},
                            "meter": None,
                            "nickname": None,
                            "product": "prod_RIDuesaY2hbu6F",
                            "tiers_mode": None,
                            "transform_usage": None,
                            "trial_period_days": None,
                            "usage_type": "licensed"
                        },
                        "price": {
                            "id": "price_1QPdeSL1MLd6bigC8hHq4zFm",
                            "object": "price",
                            "active": True,
                            "billing_scheme": "per_unit",
                            "created": 1732684740,
                            "currency": "usd",
                            "custom_unit_amount": None,
                            "livemode": False,
                            "lookup_key": "1_month_5000_recurring_donation",
                            "metadata": {},
                            "nickname": None,
                            "product": "prod_RIDuesaY2hbu6F",
                            "recurring": {
                                "aggregate_usage": None,
                                "interval": "month",
                                "interval_count": 1,
                                "meter": None,
                                "trial_period_days": None,
                                "usage_type": "licensed"
                            },
                            "tax_behavior": "unspecified",
                            "tiers_mode": None,
                            "transform_quantity": None,
                            "type": "recurring",
                            "unit_amount": 5000,
                            "unit_amount_decimal": "5000"
                        },
                        "quantity": 1,
                        "subscription": "sub_1QjZZiL1MLd6bigC1zMiPpEz",
                        "tax_rates": []
                    }
                ],
                "has_more": False,
                "total_count": 1,
                "url": "/v1/subscription_items?subscription=sub_1QjZZiL1MLd6bigC1zMiPpEz"
            },
            "latest_invoice": "in_1QjZZiL1MLd6bigCgdJSDASj",
            "livemode": False,
            "metadata": {},
            "next_pending_invoice_item_invoice": None,
            "on_behalf_of": None,
            "pause_collection": None,
            "payment_settings": {
                "payment_method_options": None,
                "payment_method_types": None,
                "save_default_payment_method": None
            },
            "pending_invoice_item_interval": None,
            "pending_setup_intent": None,
            "pending_update": None,
            "plan": {
                "id": "price_1QPdeSL1MLd6bigC8hHq4zFm",
                "object": "plan",
                "active": True,
                "aggregate_usage": None,
                "amount": 5000,
                "amount_decimal": "5000",
                "billing_scheme": "per_unit",
                "created": 1732684740,
                "currency": "usd",
                "interval": "month",
                "interval_count": 1,
                "livemode": False,
                "metadata": {},
                "meter": None,
                "nickname": None,
                "product": "prod_RIDuesaY2hbu6F",
                "tiers_mode": None,
                "transform_usage": None,
                "trial_period_days": None,
                "usage_type": "licensed"
            },
            "quantity": 1,
            "schedule": "sub_sched_1QaNtTL1MLd6bigC9AQHNWKK",
            "start_date": 1737435600,
            "status": "active",
            "test_clock": None,
            "transfer_data": None,
            "trial_end": None,
            "trial_settings": {
                "end_behavior": {
                    "missing_payment_method": "create_invoice"
                }
            },
            "trial_start": None
        }
    },
    "livemode": False,
    "pending_webhooks": 0,
    "request": {
        "id": None,
        "idempotency_key": None
    },
    "type": "customer.subscription.created"
}

@pytest.fixture
def open_active_subscription_dict():
    return {
        "id": "evt_1PFUWHL1MLd6bigCVAZSTwAY",
        "object": "event",
        "api_version": "2022-11-15",
        "created": 1715490021,
        "data": {
            "object": {
                "id": "sub_1PFUWGL1MLd6bigCFPlOUlAD",
                "object": "subscription",
                "application": "ca_EEtbhRJHFK2etIhjyxcqXqBw3Ck05bKK",
                "application_fee_percent": None,
                "automatic_tax": {
                    "enabled": False,
                    "liability": None
                },
                "billing_cycle_anchor": 1715490020,
                "billing_cycle_anchor_config": None,
                "billing_thresholds": None,
                "cancel_at": None,
                "cancel_at_period_end": False,
                "canceled_at": None,
                "cancellation_details": {
                    "comment": None,
                    "feedback": None,
                    "reason": None
                },
                "collection_method": "charge_automatically",
                "created": 1715490020,
                "currency": "usd",
                "current_period_end": 1718168420,
                "current_period_start": 1715490020,
                "customer": "cus_Q5frnnA09N8teA",
                "days_until_due": None,
                "default_payment_method": "pm_1PFUWEL1MLd6bigCTmHNXMmz",
                "default_source": None,
                "default_tax_rates": [],
                "description": None,
                "discount": None,
                "discounts": [],
                "ended_at": None,
                "invoice_settings": {
                    "account_tax_ids": None,
                    "issuer": {
                        "type": "self"
                    }
                },
                "items": {
                    "object": "list",
                    "data": [
                        {
                            "id": "si_Q5fsKjBb2W26aP",
                            "object": "subscription_item",
                            "billing_thresholds": None,
                            "created": 1715490020,
                            "discounts": [],
                            "metadata": {},
                            "plan": {
                                "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                                "object": "plan",
                                "active": True,
                                "aggregate_usage": None,
                                "amount": 100,
                                "amount_decimal": "100",
                                "billing_scheme": "per_unit",
                                "created": 1711218898,
                                "currency": "usd",
                                "interval": "month",
                                "interval_count": 1,
                                "livemode": False,
                                "metadata": {},
                                "meter": None,
                                "nickname": None,
                                "product": "prod_Pn9imCT8L9sSWq",
                                "tiers_mode": None,
                                "transform_usage": None,
                                "trial_period_days": None,
                                "usage_type": "licensed"
                            },
                            "price": {
                                "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                                "object": "price",
                                "active": True,
                                "billing_scheme": "per_unit",
                                "created": 1711218898,
                                "currency": "usd",
                                "custom_unit_amount": None,
                                "livemode": False,
                                "lookup_key": None,
                                "metadata": {},
                                "nickname": None,
                                "product": "prod_Pn9imCT8L9sSWq",
                                "recurring": {
                                    "aggregate_usage": None,
                                    "interval": "month",
                                    "interval_count": 1,
                                    "meter": None,
                                    "trial_period_days": None,
                                    "usage_type": "licensed"
                                },
                                "tax_behavior": "exclusive",
                                "tiers_mode": None,
                                "transform_quantity": None,
                                "type": "recurring",
                                "unit_amount": 100,
                                "unit_amount_decimal": "100"
                            },
                            "quantity": 555,
                            "subscription": "sub_1PFUWGL1MLd6bigCFPlOUlAD",
                            "tax_rates": []
                        }
                    ],
                    "has_more": False,
                    "total_count": 1,
                    "url": "/v1/subscription_items?subscription=sub_1PFUWGL1MLd6bigCFPlOUlAD"
                },
                "latest_invoice": "in_1PFUWGL1MLd6bigC0GTmyKFu",
                "livemode": False,
                "metadata": {
                    "created_by": "FormAssembly - Stripe - Reference: Form 5120065 / Conn. 762535 / Resp. 338509469",
                    "campaign_code": "F000"
                },
                "next_pending_invoice_item_invoice": None,
                "on_behalf_of": None,
                "pause_collection": None,
                "payment_settings": {
                    "payment_method_options": None,
                    "payment_method_types": None,
                    "save_default_payment_method": "off"
                },
                "pending_invoice_item_interval": None,
                "pending_setup_intent": None,
                "pending_update": None,
                "plan": {
                    "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                    "object": "plan",
                    "active": True,
                    "aggregate_usage": None,
                    "amount": 100,
                    "amount_decimal": "100",
                    "billing_scheme": "per_unit",
                    "created": 1711218898,
                    "currency": "usd",
                    "interval": "month",
                    "interval_count": 1,
                    "livemode": False,
                    "metadata": {},
                    "meter": None,
                    "nickname": None,
                    "product": "prod_Pn9imCT8L9sSWq",
                    "tiers_mode": None,
                    "transform_usage": None,
                    "trial_period_days": None,
                    "usage_type": "licensed"
                },
                "quantity": 555,
                "schedule": None,
                "start_date": 1715490020,
                "status": "active",
                "test_clock": None,
                "transfer_data": None,
                "trial_end": None,
                "trial_settings": {
                    "end_behavior": {
                        "missing_payment_method": "create_invoice"
                    }
                },
                "trial_start": None
            }
        },
        "livemode": False,
        "pending_webhooks": 0,
        "request": {
            "id": "req_EY9LePtsEx7kgF",
            "idempotency_key": "4d702001-ef82-40a5-8075-6aa9895f50cc"
        },
        "type": "customer.subscription.created"
    }


@pytest.fixture
def canceled_subscription_dict():
    return {
        "id": "evt_1PCBNeL1MLd6bigCMmvVHJoF",
        "object": "event",
        "api_version": "2022-11-15",
        "created": 1714701466,
        "data": {
            "object": {
                "id": "sub_1P1hCDL1MLd6bigCTMM9YrD9",
                "object": "subscription",
                "application": "ca_EEtbhRJHFK2etIhjyxcqXqBw3Ck05bKK",
                "application_fee_percent": None,
                "automatic_tax": {
                    "enabled": False,
                    "liability": None
                },
                "billing_cycle_anchor": 1712202157,
                "billing_cycle_anchor_config": None,
                "billing_thresholds": None,
                "cancel_at": None,
                "cancel_at_period_end": False,
                "canceled_at": 1714701465,
                "cancellation_details": {
                    "comment": None,
                    "feedback": None,
                    "reason": "cancellation_requested"
                },
                "collection_method": "charge_automatically",
                "created": 1712202157,
                "currency": "usd",
                "current_period_end": 1714794157,
                "current_period_start": 1712202157,
                "customer": "cus_PrQ2qIHY8Jzywm",
                "days_until_due": None,
                "default_payment_method": "pm_1P1hCCL1MLd6bigCde45mpoC",
                "default_source": None,
                "default_tax_rates": [],
                "description": None,
                "discount": None,
                "discounts": [],
                "ended_at": 1714701465,
                "invoice_settings": {
                    "account_tax_ids": None,
                    "issuer": {
                        "type": "self"
                    }
                },
                "items": {
                    "object": "list",
                    "data": [
                        {
                            "id": "si_PrQ28sJ5vSov5C",
                            "object": "subscription_item",
                            "billing_thresholds": None,
                            "created": 1712202158,
                            "discounts": [],
                            "metadata": {},
                            "plan": {
                                "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                                "object": "plan",
                                "active": True,
                                "aggregate_usage": None,
                                "amount": 100,
                                "amount_decimal": "100",
                                "billing_scheme": "per_unit",
                                "created": 1711218898,
                                "currency": "usd",
                                "interval": "month",
                                "interval_count": 1,
                                "livemode": False,
                                "metadata": {},
                                "meter": None,
                                "nickname": None,
                                "product": "prod_Pn9imCT8L9sSWq",
                                "tiers_mode": None,
                                "transform_usage": None,
                                "trial_period_days": None,
                                "usage_type": "licensed"
                            },
                            "price": {
                                "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                                "object": "price",
                                "active": True,
                                "billing_scheme": "per_unit",
                                "created": 1711218898,
                                "currency": "usd",
                                "custom_unit_amount": None,
                                "livemode": False,
                                "lookup_key": None,
                                "metadata": {},
                                "nickname": None,
                                "product": "prod_Pn9imCT8L9sSWq",
                                "recurring": {
                                    "aggregate_usage": None,
                                    "interval": "month",
                                    "interval_count": 1,
                                    "meter": None,
                                    "trial_period_days": None,
                                    "usage_type": "licensed"
                                },
                                "tax_behavior": "exclusive",
                                "tiers_mode": None,
                                "transform_quantity": None,
                                "type": "recurring",
                                "unit_amount": 100,
                                "unit_amount_decimal": "100"
                            },
                            "quantity": 1,
                            "subscription": "sub_1P1hCDL1MLd6bigCTMM9YrD9",
                            "tax_rates": []
                        }
                    ],
                    "has_more": False,
                    "total_count": 1,
                    "url": "/v1/subscription_items?subscription=sub_1P1hCDL1MLd6bigCTMM9YrD9"
                },
                "latest_invoice": "in_1P1hCDL1MLd6bigCHsJ3eO2v",
                "livemode": False,
                "metadata": {
                    "created_by": "FormAssembly - Stripe - Reference: Form 5120065 / Conn. 762535 / Resp. 334286604"
                },
                "next_pending_invoice_item_invoice": None,
                "on_behalf_of": None,
                "pause_collection": None,
                "payment_settings": {
                    "payment_method_options": None,
                    "payment_method_types": None,
                    "save_default_payment_method": "off"
                },
                "pending_invoice_item_interval": None,
                "pending_setup_intent": None,
                "pending_update": None,
                "plan": {
                    "id": "price_1OxZPCL1MLd6bigCglyGWwz9",
                    "object": "plan",
                    "active": True,
                    "aggregate_usage": None,
                    "amount": 100,
                    "amount_decimal": "100",
                    "billing_scheme": "per_unit",
                    "created": 1711218898,
                    "currency": "usd",
                    "interval": "month",
                    "interval_count": 1,
                    "livemode": False,
                    "metadata": {},
                    "meter": None,
                    "nickname": None,
                    "product": "prod_Pn9imCT8L9sSWq",
                    "tiers_mode": None,
                    "transform_usage": None,
                    "trial_period_days": None,
                    "usage_type": "licensed"
                },
                "quantity": 1,
                "schedule": None,
                "start_date": 1712202157,
                "status": "canceled",
                "test_clock": None,
                "transfer_data": None,
                "trial_end": None,
                "trial_settings": {
                    "end_behavior": {
                        "missing_payment_method": "create_invoice"
                    }
                },
                "trial_start": None
            }
        },
        "livemode": False,
        "pending_webhooks": 0,
        "request": {
            "id": "req_5zMHKtj6Nq5ARg",
            "idempotency_key": None
        },
        "type": "customer.subscription.deleted"
    }

@pytest.fixture
def subscription_error_6_17_25():
    return {'id': 'evt_1RaUDYL1MLd6bigC0WdU0JkN', 'object': 'event', 'api_version': '2022-11-15', 'created': 1750046420, 'data': {'object': {'id': 'sub_1REN9mL1MLd6bigCSNBk9u3r', 'object': 'subscription', 'application': None, 'application_fee_percent': None, 'automatic_tax': {'disabled_reason': None, 'enabled': False, 'liability': None}, 'billing_cycle_anchor': 1744776000, 'billing_cycle_anchor_config': None, 'billing_thresholds': None, 'cancel_at': None, 'cancel_at_period_end': False, 'canceled_at': None, 'cancellation_details': {'comment': None, 'feedback': None, 'reason': None}, 'collection_method': 'charge_automatically', 'created': 1744776000, 'currency': 'usd', 'current_period_end': 1752638400, 'current_period_start': 1750046400, 'customer': 'cus_RlOXMOicQ2qZBf', 'days_until_due': None, 'default_payment_method': 'pm_1R9r46L1MLd6bigCdQew6xDV', 'default_source': None, 'default_tax_rates': [], 'description': None, 'discount': None, 'discounts': [], 'ended_at': None, 'invoice_settings': {'account_tax_ids': None, 'issuer': {'type': 'self'}}, 'items': {'object': 'list', 'data': [{'id': 'si_S8eSrPvj1FT04z', 'object': 'subscription_item', 'billing_thresholds': None, 'created': 1744776063, 'current_period_end': 1752638400, 'current_period_start': 1750046400, 'discounts': [], 'metadata': {}, 'plan': {'id': 'price_1RBSf4L1MLd6bigCrY6gPp0k', 'object': 'plan', 'active': True, 'aggregate_usage': None, 'amount': 4000, 'amount_decimal': '4000', 'billing_scheme': 'per_unit', 'created': 1744082238, 'currency': 'usd', 'interval': 'month', 'interval_count': 1, 'livemode': True, 'metadata': {}, 'meter': None, 'nickname': None, 'product': 'prod_S4kuPugIiCaL75', 'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None, 'usage_type': 'licensed'}, 'price': {'id': 'price_1RBSf4L1MLd6bigCrY6gPp0k', 'object': 'price', 'active': True, 'billing_scheme': 'per_unit', 'created': 1744082238, 'currency': 'usd', 'custom_unit_amount': None, 'livemode': True, 'lookup_key': '1_month_4000_recurring_donation', 'metadata': {}, 'nickname': None, 'product': 'prod_S4kuPugIiCaL75', 'recurring': {'aggregate_usage': None, 'interval': 'month', 'interval_count': 1, 'meter': None, 'trial_period_days': None, 'usage_type': 'licensed'}, 'tax_behavior': 'unspecified', 'tiers_mode': None, 'transform_quantity': None, 'type': 'recurring', 'unit_amount': 4000, 'unit_amount_decimal': '4000'}, 'quantity': 1, 'subscription': 'sub_1REN9mL1MLd6bigCSNBk9u3r', 'tax_rates': []}], 'has_more': False, 'total_count': 1, 'url': '/v1/subscription_items?subscription=sub_1REN9mL1MLd6bigCSNBk9u3r'}, 'latest_invoice': 'in_1RaUDXL1MLd6bigCFuu6Alrk', 'livemode': True, 'metadata': {}, 'next_pending_invoice_item_invoice': None, 'on_behalf_of': None, 'pause_collection': None, 'payment_settings': {'payment_method_options': None, 'payment_method_types': None, 'save_default_payment_method': None}, 'pending_invoice_item_interval': None, 'pending_setup_intent': None, 'pending_update': None, 'plan': {'id': 'price_1RBSf4L1MLd6bigCrY6gPp0k', 'object': 'plan', 'active': True, 'aggregate_usage': None, 'amount': 4000, 'amount_decimal': '4000', 'billing_scheme': 'per_unit', 'created': 1744082238, 'currency': 'usd', 'interval': 'month', 'interval_count': 1, 'livemode': True, 'metadata': {}, 'meter': None, 'nickname': None, 'product': 'prod_S4kuPugIiCaL75', 'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None, 'usage_type': 'licensed'}, 'quantity': 1, 'schedule': None, 'start_date': 1744776000, 'status': 'active', 'test_clock': None, 'transfer_data': None, 'trial_end': None, 'trial_settings': {'end_behavior': {'missing_payment_method': 'create_invoice'}}, 'trial_start': None}, 'previous_attributes': {'current_period_end': 1750046400, 'current_period_start': 1747368000, 'items': {'data': [{'id': 'si_S8eSrPvj1FT04z', 'object': 'subscription_item', 'billing_thresholds': None, 'created': 1744776063, 'current_period_end': 1750046400, 'current_period_start': 1747368000, 'discounts': [], 'metadata': {}, 'plan': {'id': 'price_1RBSf4L1MLd6bigCrY6gPp0k', 'object': 'plan', 'active': True, 'aggregate_usage': None, 'amount': 4000, 'amount_decimal': '4000', 'billing_scheme': 'per_unit', 'created': 1744082238, 'currency': 'usd', 'interval': 'month', 'interval_count': 1, 'livemode': True, 'metadata': {}, 'meter': None, 'nickname': None, 'product': 'prod_S4kuPugIiCaL75', 'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None, 'usage_type': 'licensed'}, 'price': {'id': 'price_1RBSf4L1MLd6bigCrY6gPp0k', 'object': 'price', 'active': True, 'billing_scheme': 'per_unit', 'created': 1744082238, 'currency': 'usd', 'custom_unit_amount': None, 'livemode': True, 'lookup_key': '1_month_4000_recurring_donation', 'metadata': {}, 'nickname': None, 'product': 'prod_S4kuPugIiCaL75', 'recurring': {'aggregate_usage': None, 'interval': 'month', 'interval_count': 1, 'meter': None, 'trial_period_days': None, 'usage_type': 'licensed'}, 'tax_behavior': 'unspecified', 'tiers_mode': None, 'transform_quantity': None, 'type': 'recurring', 'unit_amount': 4000, 'unit_amount_decimal': '4000'}, 'quantity': 1, 'subscription': 'sub_1REN9mL1MLd6bigCSNBk9u3r', 'tax_rates': []}]}, 'latest_invoice': 'in_1RPFS6L1MLd6bigCB01cplQo'}}, 'livemode': True, 'pending_webhooks': 1, 'request': {'id': None, 'idempotency_key': None}, 'type': 'customer.subscription.updated'}

@pytest.fixture
def subscription_error_8_18_24():
    return json.dumps(
        {'id': 'evt_1PozfsL1MLd6bigCILWLFYk3', 'object': 'event', 'api_version': '2022-11-15', 'created': 1723951260,
         'data': {'object': {'id': 'sub_1PdkqmL1MLd6bigCvl9AfiPa', 'object': 'subscription',
                             'application': 'ca_EEtbhRJHFK2etIhjyxcqXqBw3Ck05bKK', 'application_fee_percent': None,
                             'automatic_tax': {'enabled': False, 'liability': None}, 'billing_cycle_anchor': 1721272668,
                             'billing_cycle_anchor_config': None, 'billing_thresholds': None, 'cancel_at': None,
                             'cancel_at_period_end': False, 'canceled_at': None,
                             'cancellation_details': {'comment': None, 'feedback': None, 'reason': None},
                             'collection_method': 'charge_automatically', 'created': 1721272668, 'currency': 'usd',
                             'current_period_end': 1726629468, 'current_period_start': 1723951068,
                             'customer': 'cus_QUkLINtx3jUr7v', 'days_until_due': None,
                             'default_payment_method': 'pm_1PdkqkL1MLd6bigCSceIpC60', 'default_source': None,
                             'default_tax_rates': [], 'description': None, 'discount': None, 'discounts': [],
                             'ended_at': None,
                             'invoice_settings': {'account_tax_ids': None, 'issuer': {'type': 'self'}},
                             'items': {'object': 'list', 'data': [
                                 {'id': 'si_QUkLKPwGLaWs5s', 'object': 'subscription_item', 'billing_thresholds': None,
                                  'created': 1721272669, 'discounts': [], 'metadata': {},
                                  'plan': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'plan', 'active': True,
                                           'aggregate_usage': None, 'amount': 100, 'amount_decimal': '100',
                                           'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                           'interval': 'month', 'interval_count': 1, 'livemode': False, 'metadata': {},
                                           'meter': None, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                           'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None,
                                           'usage_type': 'licensed'},
                                  'price': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'price', 'active': True,
                                            'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                            'custom_unit_amount': None, 'livemode': False, 'lookup_key': None,
                                            'metadata': {}, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                            'recurring': {'aggregate_usage': None, 'interval': 'month',
                                                          'interval_count': 1, 'meter': None, 'trial_period_days': None,
                                                          'usage_type': 'licensed'}, 'tax_behavior': 'exclusive',
                                            'tiers_mode': None, 'transform_quantity': None, 'type': 'recurring',
                                            'unit_amount': 100, 'unit_amount_decimal': '100'}, 'quantity': 444,
                                  'subscription': 'sub_1PdkqmL1MLd6bigCvl9AfiPa', 'tax_rates': []}], 'has_more': False,
                                       'total_count': 1,
                                       'url': '/v1/subscription_items?subscription=sub_1PdkqmL1MLd6bigCvl9AfiPa'},
                             'latest_invoice': 'in_1PozfrL1MLd6bigCm34AiBgp', 'livemode': False, 'metadata': {
                 'created_by': 'FormAssembly - Stripe - Reference: Form 5120065 / Conn. 762535 / Resp. 346955642',
                 'campaign_code': 'F000 - General'}, 'next_pending_invoice_item_invoice': None, 'on_behalf_of': None,
                             'pause_collection': None,
                             'payment_settings': {'payment_method_options': None, 'payment_method_types': None,
                                                  'save_default_payment_method': 'off'},
                             'pending_invoice_item_interval': None, 'pending_setup_intent': None,
                             'pending_update': None,
                             'plan': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'plan', 'active': True,
                                      'aggregate_usage': None, 'amount': 100, 'amount_decimal': '100',
                                      'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                      'interval': 'month', 'interval_count': 1, 'livemode': False, 'metadata': {},
                                      'meter': None, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                      'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None,
                                      'usage_type': 'licensed'}, 'quantity': 444, 'schedule': None,
                             'start_date': 1721272668, 'status': 'active', 'test_clock': None, 'transfer_data': None,
                             'trial_end': None,
                             'trial_settings': {'end_behavior': {'missing_payment_method': 'create_invoice'}},
                             'trial_start': None},
                  'previous_attributes': {'current_period_end': 1723951068, 'current_period_start': 1721272668,
                                          'latest_invoice': 'in_1PdkqmL1MLd6bigCLKZDEOvT'}}, 'livemode': False,
         'pending_webhooks': 1, 'request': {'id': None, 'idempotency_key': None},
         'type': 'customer.subscription.updated'})


@pytest.fixture
def subscription_update_event_dict():
    return {'id': 'evt_1PVm1GL1MLd6bigCoqQjk6zQ', 'object': 'event', 'api_version': '2022-11-15', 'created': 1719370537,
            'data': {'object': {'id': 'sub_1PVm1CL1MLd6bigCoJNJkhJi', 'object': 'subscription',
                                'application': 'ca_EEtbhRJHFK2etIhjyxcqXqBw3Ck05bKK', 'application_fee_percent': None,
                                'automatic_tax': {'enabled': False, 'liability': None},
                                'billing_cycle_anchor': 1719370533,
                                'billing_cycle_anchor_config': None, 'billing_thresholds': None, 'cancel_at': None,
                                'cancel_at_period_end': False, 'canceled_at': None,
                                'cancellation_details': {'comment': None, 'feedback': None, 'reason': None},
                                'collection_method': 'charge_automatically', 'created': 1719370533, 'currency': 'usd',
                                'current_period_end': 1721962533, 'current_period_start': 1719370533,
                                'customer': 'cus_QMV1TWElciMIsp', 'days_until_due': None,
                                'default_payment_method': 'pm_1PVm1AL1MLd6bigCRlSbSUHf', 'default_source': None,
                                'default_tax_rates': [], 'description': None, 'discount': None, 'discounts': [],
                                'ended_at': None,
                                'invoice_settings': {'account_tax_ids': None, 'issuer': {'type': 'self'}},
                                'items': {'object': 'list', 'data': [
                                    {'id': 'si_QMV1IuZHIUIeZT', 'object': 'subscription_item',
                                     'billing_thresholds': None,
                                     'created': 1719370534, 'discounts': [], 'metadata': {},
                                     'plan': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'plan', 'active': True,
                                              'aggregate_usage': None, 'amount': 100, 'amount_decimal': '100',
                                              'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                              'interval': 'month', 'interval_count': 1, 'livemode': False,
                                              'metadata': {},
                                              'meter': None, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                              'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None,
                                              'usage_type': 'licensed'},
                                     'price': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'price',
                                               'active': True,
                                               'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                               'custom_unit_amount': None, 'livemode': False, 'lookup_key': None,
                                               'metadata': {}, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                               'recurring': {'aggregate_usage': None, 'interval': 'month',
                                                             'interval_count': 1, 'meter': None,
                                                             'trial_period_days': None,
                                                             'usage_type': 'licensed'}, 'tax_behavior': 'exclusive',
                                               'tiers_mode': None, 'transform_quantity': None, 'type': 'recurring',
                                               'unit_amount': 100, 'unit_amount_decimal': '100'}, 'quantity': 987,
                                     'subscription': 'sub_1PVm1CL1MLd6bigCoJNJkhJi', 'tax_rates': []}],
                                          'has_more': False,
                                          'total_count': 1,
                                          'url': '/v1/subscription_items?subscription=sub_1PVm1CL1MLd6bigCoJNJkhJi'},
                                'latest_invoice': 'in_1PVm1CL1MLd6bigCx2nkQ8lL', 'livemode': False, 'metadata': {
                    'created_by': 'FormAssembly - Stripe - Reference: Form 5120065 / Conn. 762535 / Resp. 343927769'},
                                'next_pending_invoice_item_invoice': None, 'on_behalf_of': None,
                                'pause_collection': None,
                                'payment_settings': {'payment_method_options': None, 'payment_method_types': None,
                                                     'save_default_payment_method': 'off'},
                                'pending_invoice_item_interval': None, 'pending_setup_intent': None,
                                'pending_update': None,
                                'plan': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'plan', 'active': True,
                                         'aggregate_usage': None, 'amount': 100, 'amount_decimal': '100',
                                         'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                         'interval': 'month', 'interval_count': 1, 'livemode': False, 'metadata': {},
                                         'meter': None, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                         'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None,
                                         'usage_type': 'licensed'}, 'quantity': 987, 'schedule': None,
                                'start_date': 1719370533, 'status': 'active', 'test_clock': None, 'transfer_data': None,
                                'trial_end': None,
                                'trial_settings': {'end_behavior': {'missing_payment_method': 'create_invoice'}},
                                'trial_start': None}, 'previous_attributes': {'status': 'incomplete'}},
            'livemode': False,
            'pending_webhooks': 1,
            'request': {'id': 'req_37pTMnB2c23SCI', 'idempotency_key': 'e4a69b4e-d993-4a85-9dab-061028dd3245'},
            'type': 'customer.subscription.updated'}


# TODO: make sure to grab actual create event json from Stripe (this is just copied form update event json)
@pytest.fixture
def subscription_create_event_dict():
    return {'id': 'evt_1PVm1GL1MLd6bigCoqQjk6zQ', 'object': 'event', 'api_version': '2022-11-15', 'created': 1719370537,
            'data': {'object': {'id': 'sub_1PVm1CL1MLd6bigCoJNJkhJi', 'object': 'subscription',
                                'application': 'ca_EEtbhRJHFK2etIhjyxcqXqBw3Ck05bKK', 'application_fee_percent': None,
                                'automatic_tax': {'enabled': False, 'liability': None},
                                'billing_cycle_anchor': 1719370533,
                                'billing_cycle_anchor_config': None, 'billing_thresholds': None, 'cancel_at': None,
                                'cancel_at_period_end': False, 'canceled_at': None,
                                'cancellation_details': {'comment': None, 'feedback': None, 'reason': None},
                                'collection_method': 'charge_automatically', 'created': 1719370533, 'currency': 'usd',
                                'current_period_end': 1721962533, 'current_period_start': 1719370533,
                                'customer': 'cus_QMV1TWElciMIsp', 'days_until_due': None,
                                'default_payment_method': 'pm_1PVm1AL1MLd6bigCRlSbSUHf', 'default_source': None,
                                'default_tax_rates': [], 'description': None, 'discount': None, 'discounts': [],
                                'ended_at': None,
                                'invoice_settings': {'account_tax_ids': None, 'issuer': {'type': 'self'}},
                                'items': {'object': 'list', 'data': [
                                    {'id': 'si_QMV1IuZHIUIeZT', 'object': 'subscription_item',
                                     'billing_thresholds': None,
                                     'created': 1719370534, 'discounts': [], 'metadata': {},
                                     'plan': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'plan', 'active': True,
                                              'aggregate_usage': None, 'amount': 100, 'amount_decimal': '100',
                                              'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                              'interval': 'month', 'interval_count': 1, 'livemode': False,
                                              'metadata': {},
                                              'meter': None, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                              'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None,
                                              'usage_type': 'licensed'},
                                     'price': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'price',
                                               'active': True,
                                               'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                               'custom_unit_amount': None, 'livemode': False, 'lookup_key': None,
                                               'metadata': {}, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                               'recurring': {'aggregate_usage': None, 'interval': 'month',
                                                             'interval_count': 1, 'meter': None,
                                                             'trial_period_days': None,
                                                             'usage_type': 'licensed'}, 'tax_behavior': 'exclusive',
                                               'tiers_mode': None, 'transform_quantity': None, 'type': 'recurring',
                                               'unit_amount': 100, 'unit_amount_decimal': '100'}, 'quantity': 987,
                                     'subscription': 'sub_1PVm1CL1MLd6bigCoJNJkhJi', 'tax_rates': []}],
                                          'has_more': False,
                                          'total_count': 1,
                                          'url': '/v1/subscription_items?subscription=sub_1PVm1CL1MLd6bigCoJNJkhJi'},
                                'latest_invoice': 'in_1PVm1CL1MLd6bigCx2nkQ8lL', 'livemode': False, 'metadata': {
                    'created_by': 'FormAssembly - Stripe - Reference: Form 5120065 / Conn. 762535 / Resp. 343927769'},
                                'next_pending_invoice_item_invoice': None, 'on_behalf_of': None,
                                'pause_collection': None,
                                'payment_settings': {'payment_method_options': None, 'payment_method_types': None,
                                                     'save_default_payment_method': 'off'},
                                'pending_invoice_item_interval': None, 'pending_setup_intent': None,
                                'pending_update': None,
                                'plan': {'id': 'price_1OxZPCL1MLd6bigCglyGWwz9', 'object': 'plan', 'active': True,
                                         'aggregate_usage': None, 'amount': 100, 'amount_decimal': '100',
                                         'billing_scheme': 'per_unit', 'created': 1711218898, 'currency': 'usd',
                                         'interval': 'month', 'interval_count': 1, 'livemode': False, 'metadata': {},
                                         'meter': None, 'nickname': None, 'product': 'prod_Pn9imCT8L9sSWq',
                                         'tiers_mode': None, 'transform_usage': None, 'trial_period_days': None,
                                         'usage_type': 'licensed'}, 'quantity': 987, 'schedule': None,
                                'start_date': 1719370533, 'status': 'active', 'test_clock': None, 'transfer_data': None,
                                'trial_end': None,
                                'trial_settings': {'end_behavior': {'missing_payment_method': 'create_invoice'}},
                                'trial_start': None}, 'previous_attributes': {'status': 'incomplete'}},
            'livemode': False,
            'pending_webhooks': 1,
            'request': {'id': 'req_37pTMnB2c23SCI', 'idempotency_key': 'e4a69b4e-d993-4a85-9dab-061028dd3245'},
            'type': 'customer.subscription.updated'}

@pytest.fixture
def subscription_delete_event_with_subscription_schedule():
    return {
    "id": "evt_1S3qpPL1MLd6bigCqJVEBtoZ",
    "object": "event",
    "api_version": "2022-11-15",
    "created": 1757044846,
    "data": {
        "object": {
            "id": "sub_1RAcjPL1MLd6bigCWjE9Ed0C",
            "object": "subscription",
            "application": None,
            "application_fee_percent": None,
            "automatic_tax": {
                "disabled_reason": None,
                "enabled": False,
                "liability": None,
            },
            "billing_cycle_anchor": 1743882619,
            "billing_cycle_anchor_config": None,
            "billing_mode": {"type": "classic"},
            "billing_thresholds": None,
            "cancel_at": 1757044800,
            "cancel_at_period_end": False,
            "canceled_at": 1743882619,
            "cancellation_details": {
                "comment": None,
                "feedback": None,
                "reason": "cancellation_requested",
            },
            "collection_method": "charge_automatically",
            "created": 1743882619,
            "currency": "usd",
            "current_period_end": 1757044800,
            "current_period_start": 1754423419,
            "customer": "cus_RlOXLIEqRjPfKU",
            "days_until_due": None,
            "default_payment_method": None,
            "default_source": None,
            "default_tax_rates": [],
            "description": None,
            "discount": None,
            "discounts": [],
            "ended_at": 1757044800,
            "invoice_settings": {"account_tax_ids": None, "issuer": {"type": "self"}},
            "items": {
                "object": "list",
                "data": [
                    {
                        "id": "si_S4mHnzF32H3uDw",
                        "object": "subscription_item",
                        "billing_thresholds": None,
                        "created": 1743882620,
                        "current_period_end": 1757044800,
                        "current_period_start": 1754423419,
                        "discounts": [],
                        "metadata": {},
                        "plan": {
                            "id": "price_1RAcjPL1MLd6bigCyIIvSlDH",
                            "object": "plan",
                            "active": True,
                            "aggregate_usage": None,
                            "amount": 35000,
                            "amount_decimal": "35000",
                            "billing_scheme": "per_unit",
                            "created": 1743882619,
                            "currency": "usd",
                            "interval": "month",
                            "interval_count": 1,
                            "livemode": True,
                            "metadata": {},
                            "meter": None,
                            "nickname": None,
                            "product": "prod_S4kuPugIiCaL75",
                            "tiers_mode": None,
                            "transform_usage": None,
                            "trial_period_days": None,
                            "usage_type": "licensed",
                        },
                        "price": {
                            "id": "price_1RAcjPL1MLd6bigCyIIvSlDH",
                            "object": "price",
                            "active": True,
                            "billing_scheme": "per_unit",
                            "created": 1743882619,
                            "currency": "usd",
                            "custom_unit_amount": None,
                            "livemode": True,
                            "lookup_key": "1_month_35000_recurring_donation",
                            "metadata": {},
                            "nickname": None,
                            "product": "prod_S4kuPugIiCaL75",
                            "recurring": {
                                "aggregate_usage": None,
                                "interval": "month",
                                "interval_count": 1,
                                "meter": None,
                                "trial_period_days": None,
                                "usage_type": "licensed",
                            },
                            "tax_behavior": "unspecified",
                            "tiers_mode": None,
                            "transform_quantity": None,
                            "type": "recurring",
                            "unit_amount": 35000,
                            "unit_amount_decimal": "35000",
                        },
                        "quantity": 1,
                        "subscription": "sub_1RAcjPL1MLd6bigCWjE9Ed0C",
                        "tax_rates": [],
                    }
                ],
                "has_more": False,
                "total_count": 1,
                "url": "/v1/subscription_items?subscription=sub_1RAcjPL1MLd6bigCWjE9Ed0C",
            },
            "latest_invoice": "in_1RsqsML1MLd6bigCUhmGxdFt",
            "livemode": True,
            "metadata": {},
            "next_pending_invoice_item_invoice": None,
            "on_behalf_of": None,
            "pause_collection": None,
            "payment_settings": {
                "payment_method_options": None,
                "payment_method_types": None,
                "save_default_payment_method": None,
            },
            "pending_invoice_item_interval": None,
            "pending_setup_intent": None,
            "pending_update": None,
            "plan": {
                "id": "price_1RAcjPL1MLd6bigCyIIvSlDH",
                "object": "plan",
                "active": True,
                "aggregate_usage": None,
                "amount": 35000,
                "amount_decimal": "35000",
                "billing_scheme": "per_unit",
                "created": 1743882619,
                "currency": "usd",
                "interval": "month",
                "interval_count": 1,
                "livemode": True,
                "metadata": {},
                "meter": None,
                "nickname": None,
                "product": "prod_S4kuPugIiCaL75",
                "tiers_mode": None,
                "transform_usage": None,
                "trial_period_days": None,
                "usage_type": "licensed",
            },
            "quantity": 1,
            "schedule": "sub_sched_1RAcjPL1MLd6bigCVgzyYshi",
            "start_date": 1743825600,
            "status": "canceled",
            "test_clock": None,
            "transfer_data": None,
            "trial_end": None,
            "trial_settings": {
                "end_behavior": {"missing_payment_method": "create_invoice"}
            },
            "trial_start": None,
        }
    },
    "livemode": True,
    "pending_webhooks": 1,
    "request": {"id": None, "idempotency_key": None},
    "type": "customer.subscription.deleted",
}


@pytest.fixture
def subscription_delete_event_dict():
    return {
    "id": "evt_1S1rUoL1MLd6bigCloyJuvMZ",
    "object": "event",
    "api_version": "2022-11-15",
    "created": 1756570758,
    "data": {
        "object": {
            "id": "sub_1RUTY6L1MLd6bigCat7MLeBK",
            "object": "subscription",
            "application": "ca_EEtbpNfCXuyxRLnevQm4k27P4HUXWUWm",
            "application_fee_percent": None,
            "automatic_tax": {
                "disabled_reason": None,
                "enabled": False,
                "liability": None,
            },
            "billing_cycle_anchor": 1748613882,
            "billing_cycle_anchor_config": None,
            "billing_mode": {"type": "classic"},
            "billing_thresholds": None,
            "cancel_at": None,
            "cancel_at_period_end": False,
            "canceled_at": 1756570758,
            "cancellation_details": {
                "comment": None,
                "feedback": None,
                "reason": "cancellation_requested",
            },
            "collection_method": "charge_automatically",
            "created": 1748613882,
            "currency": "usd",
            "current_period_end": 1759241082,
            "current_period_start": 1756562682,
            "customer": "cus_SPI84kGriaE3Lc",
            "days_until_due": None,
            "default_payment_method": "pm_1RUTY5L1MLd6bigCdUX9MQgF",
            "default_source": None,
            "default_tax_rates": [],
            "description": None,
            "discount": None,
            "discounts": [],
            "ended_at": 1756570758,
            "invoice_settings": {"account_tax_ids": None, "issuer": {"type": "self"}},
            "items": {
                "object": "list",
                "data": [
                    {
                        "id": "si_SPI8i7XI8aV9BP",
                        "object": "subscription_item",
                        "billing_thresholds": None,
                        "created": 1748613883,
                        "current_period_end": 1759241082,
                        "current_period_start": 1756562682,
                        "discounts": [],
                        "metadata": {},
                        "plan": {
                            "id": "price_1R4YqtL1MLd6bigCwuZll9ef",
                            "object": "plan",
                            "active": True,
                            "aggregate_usage": None,
                            "amount": 10000,
                            "amount_decimal": "10000",
                            "billing_scheme": "per_unit",
                            "created": 1742437739,
                            "currency": "usd",
                            "interval": "month",
                            "interval_count": 1,
                            "livemode": True,
                            "metadata": {},
                            "meter": None,
                            "nickname": None,
                            "product": "prod_RyVsi7nNSt1mqK",
                            "tiers_mode": None,
                            "transform_usage": None,
                            "trial_period_days": None,
                            "usage_type": "licensed",
                        },
                        "price": {
                            "id": "price_1R4YqtL1MLd6bigCwuZll9ef",
                            "object": "price",
                            "active": True,
                            "billing_scheme": "per_unit",
                            "created": 1742437739,
                            "currency": "usd",
                            "custom_unit_amount": None,
                            "livemode": True,
                            "lookup_key": None,
                            "metadata": {},
                            "nickname": None,
                            "product": "prod_RyVsi7nNSt1mqK",
                            "recurring": {
                                "aggregate_usage": None,
                                "interval": "month",
                                "interval_count": 1,
                                "meter": None,
                                "trial_period_days": None,
                                "usage_type": "licensed",
                            },
                            "tax_behavior": "exclusive",
                            "tiers_mode": None,
                            "transform_quantity": None,
                            "type": "recurring",
                            "unit_amount": 10000,
                            "unit_amount_decimal": "10000",
                        },
                        "quantity": 1,
                        "subscription": "sub_1RUTY6L1MLd6bigCat7MLeBK",
                        "tax_rates": [],
                    }
                ],
                "has_more": False,
                "total_count": 1,
                "url": "/v1/subscription_items?subscription=sub_1RUTY6L1MLd6bigCat7MLeBK",
            },
            "latest_invoice": "in_1S1pP7L1MLd6bigCd6migt2Y",
            "livemode": True,
            "metadata": {
                "created_by": "FormAssembly - Stripe Connector - Reference: Form 5172191 / Conn. 827226 / Resp. 378657054",
                "campaign_code": "C0425",
            },
            "next_pending_invoice_item_invoice": None,
            "on_behalf_of": None,
            "pause_collection": None,
            "payment_settings": {
                "payment_method_options": None,
                "payment_method_types": None,
                "save_default_payment_method": "off",
            },
            "pending_invoice_item_interval": None,
            "pending_setup_intent": None,
            "pending_update": None,
            "plan": {
                "id": "price_1R4YqtL1MLd6bigCwuZll9ef",
                "object": "plan",
                "active": True,
                "aggregate_usage": None,
                "amount": 10000,
                "amount_decimal": "10000",
                "billing_scheme": "per_unit",
                "created": 1742437739,
                "currency": "usd",
                "interval": "month",
                "interval_count": 1,
                "livemode": True,
                "metadata": {},
                "meter": None,
                "nickname": None,
                "product": "prod_RyVsi7nNSt1mqK",
                "tiers_mode": None,
                "transform_usage": None,
                "trial_period_days": None,
                "usage_type": "licensed",
            },
            "quantity": 1,
            "schedule": None,
            "start_date": 1748613882,
            "status": "canceled",
            "test_clock": None,
            "transfer_data": None,
            "trial_end": None,
            "trial_settings": {
                "end_behavior": {"missing_payment_method": "create_invoice"}
            },
            "trial_start": None,
        }
    },
    "livemode": True,
    "pending_webhooks": 1,
    "request": {"id": "req_UPUzGTNY5EyQ5q", "idempotency_key": None},
    "type": "customer.subscription.deleted"
}

@pytest.fixture
def subscription_error_10_11_25_mock():
    return {
    "id": "evt_1SH4yNL1MLd6bigCNsFhRi2H",
    "object": "event",
    "api_version": "2022-11-15",
    "created": 1760197482,
    "data": {
        "object": {
            "id": "sub_1QJzmHL1MLd6bigCMp4fC6Es",
            "object": "subscription",
            "application": "ca_EEtbpNfCXuyxRLnevQm4k27P4HUXWUWm",
            "application_fee_percent": None,
            "automatic_tax": {
                "disabled_reason": None,
                "enabled": False,
                "liability": None,
            },
            "billing_cycle_anchor": 1731339825,
            "billing_cycle_anchor_config": None,
            "billing_mode": {"flexible": None, "type": "classic"},
            "billing_thresholds": None,
            "cancel_at": None,
            "cancel_at_period_end": False,
            "canceled_at": None,
            "cancellation_details": {"comment": None, "feedback": None, "reason": None},
            "collection_method": "charge_automatically",
            "created": 1731339825,
            "currency": "usd",
            "current_period_end": 1762875825,
            "current_period_start": 1760197425,
            "customer": "cus_RCOZ7rZfTQ2OcA",
            "days_until_due": None,
            "default_payment_method": "pm_1QJzmEL1MLd6bigC6F8qhewb",
            "default_source": None,
            "default_tax_rates": [],
            "description": None,
            "discount": None,
            "discounts": [],
            "ended_at": None,
            "invoice_settings": {"account_tax_ids": None, "issuer": {"type": "self"}},
            "items": {
                "object": "list",
                "data": [
                    {
                        "id": "si_RCOZXAFUFzaKAe",
                        "object": "subscription_item",
                        "billing_thresholds": None,
                        "created": 1731339825,
                        "current_period_end": 1762875825,
                        "current_period_start": 1760197425,
                        "discounts": [],
                        "metadata": {},
                        "plan": {
                            "id": "price_1Pi6ppL1MLd6bigClPLSLGOQ",
                            "object": "plan",
                            "active": True,
                            "aggregate_usage": None,
                            "amount": 100,
                            "amount_decimal": "100",
                            "billing_scheme": "per_unit",
                            "created": 1722310489,
                            "currency": "usd",
                            "interval": "month",
                            "interval_count": 1,
                            "livemode": True,
                            "metadata": {},
                            "meter": None,
                            "nickname": None,
                            "product": "prod_QZFKtVBQJh271P",
                            "tiers_mode": None,
                            "transform_usage": None,
                            "trial_period_days": None,
                            "usage_type": "licensed",
                        },
                        "price": {
                            "id": "price_1Pi6ppL1MLd6bigClPLSLGOQ",
                            "object": "price",
                            "active": True,
                            "billing_scheme": "per_unit",
                            "created": 1722310489,
                            "currency": "usd",
                            "custom_unit_amount": None,
                            "livemode": True,
                            "lookup_key": None,
                            "metadata": {},
                            "nickname": None,
                            "product": "prod_QZFKtVBQJh271P",
                            "recurring": {
                                "aggregate_usage": None,
                                "interval": "month",
                                "interval_count": 1,
                                "meter": None,
                                "trial_period_days": None,
                                "usage_type": "licensed",
                            },
                            "tax_behavior": "exclusive",
                            "tiers_mode": None,
                            "transform_quantity": None,
                            "type": "recurring",
                            "unit_amount": 100,
                            "unit_amount_decimal": "100",
                        },
                        "quantity": 40,
                        "subscription": "sub_1QJzmHL1MLd6bigCMp4fC6Es",
                        "tax_rates": [],
                    }
                ],
                "has_more": False,
                "total_count": 1,
                "url": "/v1/subscription_items?subscription=sub_1QJzmHL1MLd6bigCMp4fC6Es",
            },
            "latest_invoice": "in_1SH4yML1MLd6bigCMGTzKsV2",
            "livemode": True,
            "metadata": {
                "created_by": "FormAssembly - Stripe - Reference: Form 5120065 / Conn. 762535 / Resp. 358554434",
                "campaign_code": "C1024",
            },
            "next_pending_invoice_item_invoice": None,
            "on_behalf_of": None,
            "pause_collection": None,
            "payment_settings": {
                "payment_method_options": None,
                "payment_method_types": None,
                "save_default_payment_method": "off",
            },
            "pending_invoice_item_interval": None,
            "pending_setup_intent": None,
            "pending_update": None,
            "plan": {
                "id": "price_1Pi6ppL1MLd6bigClPLSLGOQ",
                "object": "plan",
                "active": True,
                "aggregate_usage": None,
                "amount": 100,
                "amount_decimal": "100",
                "billing_scheme": "per_unit",
                "created": 1722310489,
                "currency": "usd",
                "interval": "month",
                "interval_count": 1,
                "livemode": True,
                "metadata": {},
                "meter": None,
                "nickname": None,
                "product": "prod_QZFKtVBQJh271P",
                "tiers_mode": None,
                "transform_usage": None,
                "trial_period_days": None,
                "usage_type": "licensed",
            },
            "quantity": 40,
            "schedule": None,
            "start_date": 1731339825,
            "status": "active",
            "test_clock": None,
            "transfer_data": None,
            "trial_end": None,
            "trial_settings": {
                "end_behavior": {"missing_payment_method": "create_invoice"}
            },
            "trial_start": None,
        },
        "previous_attributes": {
            "current_period_end": 1760197425,
            "current_period_start": 1757605425,
            "items": {
                "data": [
                    {
                        "id": "si_RCOZXAFUFzaKAe",
                        "object": "subscription_item",
                        "billing_thresholds": None,
                        "created": 1731339825,
                        "current_period_end": 1760197425,
                        "current_period_start": 1757605425,
                        "discounts": [],
                        "metadata": {},
                        "plan": {
                            "id": "price_1Pi6ppL1MLd6bigClPLSLGOQ",
                            "object": "plan",
                            "active": True,
                            "aggregate_usage": None,
                            "amount": 100,
                            "amount_decimal": "100",
                            "billing_scheme": "per_unit",
                            "created": 1722310489,
                            "currency": "usd",
                            "interval": "month",
                            "interval_count": 1,
                            "livemode": True,
                            "metadata": {},
                            "meter": None,
                            "nickname": None,
                            "product": "prod_QZFKtVBQJh271P",
                            "tiers_mode": None,
                            "transform_usage": None,
                            "trial_period_days": None,
                            "usage_type": "licensed",
                        },
                        "price": {
                            "id": "price_1Pi6ppL1MLd6bigClPLSLGOQ",
                            "object": "price",
                            "active": True,
                            "billing_scheme": "per_unit",
                            "created": 1722310489,
                            "currency": "usd",
                            "custom_unit_amount": None,
                            "livemode": True,
                            "lookup_key": None,
                            "metadata": {},
                            "nickname": None,
                            "product": "prod_QZFKtVBQJh271P",
                            "recurring": {
                                "aggregate_usage": None,
                                "interval": "month",
                                "interval_count": 1,
                                "meter": None,
                                "trial_period_days": None,
                                "usage_type": "licensed",
                            },
                            "tax_behavior": "exclusive",
                            "tiers_mode": None,
                            "transform_quantity": None,
                            "type": "recurring",
                            "unit_amount": 100,
                            "unit_amount_decimal": "100",
                        },
                        "quantity": 40,
                        "subscription": "sub_1QJzmHL1MLd6bigCMp4fC6Es",
                        "tax_rates": [],
                    }
                ]
            },
            "latest_invoice": "in_1S6CfdL1MLd6bigCIMLKn5RF",
        },
    },
    "livemode": True,
    "pending_webhooks": 1,
    "request": {"id": None, "idempotency_key": None},
    "type": "customer.subscription.updated",
}


